Feature/elkin delete
engmanuelricardoperez/api-golang pull request #2
Opened 2021-11-24 03:39 UTC by Elkinews

adding methods deleteAlbums & deleteAlbumsByID from feature/elkin-delete to development branch

2021-11-24 03:44 UTC, engmanuelricardoperez requested changes

2021-11-24 03:44 UTC, engmanuelricardoperez commented on main.go
> +	// a := []string{"A", "B", "C", "D", "E", "F"}
Borrar los comentarios del código

2021-11-25 01:51 UTC, Elkinews commented
changes made.

2021-11-25 01:52 UTC, Elkinews commented on main.go
> +	// a := []string{"A", "B", "C", "D", "E", "F"}
se hicieron los cambios, asociados a esta rama , hice el test agregando dos funciones
el comando git swich -c origin/feature/elkin-delete ; debe ser con el nombre de la rama , le agregamos origin por eso se creo otra rama!

2021-11-25 02:22 UTC, engmanuelricardoperez commented on main.go
> +	// a := []string{"A", "B", "C", "D", "E", "F"}
Buen trabajo!

2021-11-25 02:22 UTC, engmanuelricardoperez approved these changes

2021-11-25 02:23 UTC, merged